[default.extend-words]
HSA="HSA"
Pase="Pase"
eto="eto"
sart="sart"
ONL="ONL"
groupe="groupe"
entite="entite"
moleculaire="moleculaire"
minerales="minerales"
Ser="Ser"
Thr="Thr"
pn="pn"
splitted="splitted"
ND="ND"
Nedd="Nedd"
selectin="selectin"
CNA="CNA"
terminalis="terminalis"
homogenously="homogenously"
superioris="superioris"
regio="regio"
als="als"
AER="AER"
stimulans="stimulans"
vas="vas"
regularis="regularis"
formates="formates"
transicion="transicion"
