name: Refresh imports
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
jobs:
  diff:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.3.0
    strategy:
      max-parallel: 1
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
      - name: Refreshing imports
        run: cd src/ontology/ && make GITHUB_ACTION=true refresh-imports
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update imports
          title: 'Update all imports'
          body: |
            Updates all imports.
          assignees: matentzn
